Fix for triggering tests
Cerebellum-Network/blockchain-node pull request #310
Opened 2024-04-23 12:50 UTC by tabakopavel

### Description

### Types of Changes

- [ ] Tech Debt (Code improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Dependency upgrade (A change in substrate or any 3rd party crate version)

### Migrations and Hooks

- [ ] This change requires a runtime migration.
- [ ] Modifies `on_initialize`
- [ ] Modifies `on_finalize`

### Checklist

- [ ] Change has been tested locally.
- [ ] Change adds / updates tests.
- [ ] Changelog doc updated.

2024-04-24 11:39 UTC, yahortsaryk requested changes

2024-04-24 11:39 UTC, yahortsaryk commented on .github/workflows/stage.yaml
>        - dev
Please, disable it for the `dev` branch. Read [more details in the Slack](https://cere-network.slack.com/archives/C01ALH83YVB/p1713956080572079?thread_ts=1713876820.091239&cid=C01ALH83YVB)

2024-04-24 12:09 UTC, yahortsaryk commented
There are a bunch of conflicts that have to be resolved in this PR

2024-04-25 11:37 UTC, MRamanenkau approved these changes

2024-04-25 20:00 UTC, yahortsaryk approved these changes

2024-04-30 09:21 UTC, merged