set_last_validated_era + tests
Cerebellum-Network/blockchain-node pull request #393
Opened 2024-07-09 14:34 UTC by aie0

## Description

## Types of Changes
Please select the branch type you are merging and fill in the relevant template.

- [ ] Hotfix
- [ ] Release
- [ ] Fix or Feature

## Fix or Feature

### Types of Changes

- [ ] Tech Debt (Code improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Dependency upgrade (A change in substrate or any 3rd party crate version)

### Migrations and Hooks

- [ ] This change requires a runtime migration.
- [ ] Modifies `on_initialize`
- [ ] Modifies `on_finalize`

### Checklist for Fix or Feature

- [ ] Change has been tested locally.
- [ ] Change adds / updates tests if applicable.
- [ ] Changelog doc updated.
- [ ] `spec_version` has been incremented.
- [ ] `network-relayer`'s [events](https://github.com/Cerebellum-Network/network-relayer/blob/dev-cere/shared/substrate/events.go) have been updated according to the blockchain events if applicable.
- [ ] All CI checks have been passed successfully

## Checklist for Hotfix

- [ ] Changelog has been updated.
- [ ] Crate version has been updated.
- [ ] `spec_version` has been incremented.
- [ ] Transaction version has been updated if required.
- [ ] Pull Request to `dev` has been created.
- [ ] Pull Request to `staging` has been created.
- [ ] `network-relayer`'s [events](https://github.com/Cerebellum-Network/network-relayer/blob/dev-cere/shared/substrate/events.go) have been updated according to the blockchain events if applicable.
- [ ] All CI checks have been passed successfully

## Checklist for Release

- [ ] Change has been deployed to Devnet.
- [ ] Change has been tested in Devnet.
- [ ] Change has been deployed to Qanet.
- [ ] Change has been tested in Qanet.
- [ ] Change has been deployed to Testnet.
- [ ] Change has been tested in Testnet.
- [ ] Changelog has been updated.
- [ ] Crate version has been updated.
- [ ] Spec version has been updated.
- [ ] Transaction version has been updated if required.
- [ ] All CI checks have been passed successfully

2024-07-10 09:08 UTC, yahortsaryk requested changes

2024-07-10 09:08 UTC, yahortsaryk commented on pallets/ddc-clusters/src/lib.rs
> +		fn set_last_validated_era(
I think we need to create a dedicated trait, i.e. `ClusterValidator`, and put the `set_last_validated_era` and other validation-related methods there.

The `ClusterManager` trait is supposed to contain functions related to DDC nodes management
The `ClusterProtocol` trait is supposed to contain functions related to Cluster economics
The `ClusterValidator` trait will contain validation-related functions. 

By keeping those traits separately, you decrease the chance that someone will call your `set_last_validated_era` except the `ddc-payouts` pallet.

It also makes the design clearer and the code more readable.

2024-07-15 09:07 UTC, yahortsaryk submitted a review, later dismissed

2024-07-15 09:07 UTC, yahortsaryk commented on pallets/ddc-clusters/src/migrations.rs
> +			let pre_clusters_nodes_stats_count = ClustersNodesStats::<T>::iter_keys().count();
Why do you need to check for `pre_clusters_nodes_stats_count` and `pre_clusters_nodes_count` if your migration doesn't do anything to the `ClustersNodesStats` and `ClustersNodes` storage items ?

2024-07-15 09:07 UTC, yahortsaryk commented on pallets/ddc-clusters/src/migrations.rs
> +				let mut nodes_count_by_cluster: BTreeMap<ClusterId, ClusterNodesCount> =
I don't see usages of the `nodes_count_by_cluster` variable, I think we should remove it

2024-07-15 09:07 UTC, yahortsaryk commented on pallets/ddc-clusters/src/migrations.rs
> +				pre_clusters_nodes_stats_count, 0,
This check will fail on Devnet/Qanet/Tetstnet/Mainnet as clusters on all environments have the related `ClustersNodeStats` item

2024-07-15 09:07 UTC, yahortsaryk commented on pallets/ddc-clusters/src/migrations.rs
> +			assert_eq!(
Same here, you shouldn't check for `post_clusters_nodes_count` and `post_clusters_nodes_count` if you don't modify the related storage items

2024-07-15 09:32 UTC, yahortsaryk commented on runtime/cere-dev/src/lib.rs
>  	type AuthorityId = ddc_primitives::sr25519::AuthorityId;
You should include your `pallet_ddc_clusters::migration::MigrateToV3<Runtime>` to the `Migrations` tuple of the runtime,  i.e. there should be the entry of ```type Migrations = (pallet_ddc_clusters::migration::MigrateToV3<Runtime>)``` in the `runtime/cere-dev/src/lib.rs` file

2024-07-30 13:50 UTC, yahortsaryk requested changes

2024-07-30 13:50 UTC, yahortsaryk commented on node/service/chain-specs/example.json
> +      "democracy": {
The `democracy` pallet was removed when we introduced `OpenGov`, you should remove it from the `example.json` file.

2024-07-30 13:50 UTC, yahortsaryk commented on node/service/chain-specs/example.json
> +      "council": {
The `council` pallet was removed when we introduced `OpenGov`, you should remove it from the `example.json` file.

2024-07-30 13:50 UTC, yahortsaryk commented on node/service/chain-specs/example.json
> +      "technicalCommittee": {
The `technicalCommittee` pallet was removed when we introduced `OpenGov`, you should remove it from the `example.json` file. We have `techComm` now.

2024-07-30 13:50 UTC, yahortsaryk commented on node/service/chain-specs/example.json
> +      "elections": {
The `elections` pallet was removed when we introduced OpenGov, you should remove it from the example.json file.

2024-07-30 13:50 UTC, yahortsaryk commented on node/service/chain-specs/example.json
> +      "technicalMembership": {
The `technicalMembership` pallet was removed when we introduced OpenGov, you should remove it from the example.json file.

2024-07-30 13:50 UTC, yahortsaryk commented on node/service/chain-specs/example.json
> +      "society": {
The `society"` pallet was removed previously. You should remove it from the example.json file.

2024-07-30 13:50 UTC, yahortsaryk commented on pallets/ddc-clusters/src/migrations.rs
> +			ensure!(current_version == 3, "must_upgrade");
In `post_upgrade` you can additionally check what your migrations modified, i.e. you can check that `last_validated_era_id` field is set to 0 for all clusters and there is no clusters with other values.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere-dev/src/lib.rs
> +	pallet_ddc_clusters::migrations::v2::MigrateToV2<Runtime>,
`pallet_ddc_clusters::migrations::v2` has been executed already in `cere_dev`. You should remove it from the list.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere-dev/src/lib.rs
> +	pallet_ddc_staking::migrations::v1::MigrateToV1<Runtime>,
`pallet_ddc_staking::migrations::v1` has been executed already in `cere_dev`. You should remove it from the list.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere-dev/src/lib.rs
> +	pallet_ddc_customers::migration::MigrateToV2<Runtime>,
`pallet_ddc_customers::migration::MigrateToV2` has been executed already in `cere_dev`. You should remove it from the list.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere-dev/src/lib.rs
> +	pallet_ddc_customers::migration::MigrateToV1<Runtime>,
`pallet_ddc_customers::migration::MigrateToV1` has been executed already in `cere_dev`. You should remove it from the list.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere/constants/src/lib.rs
> +// This file is part of Substrate.
This file (`runtime/cere/constants/src/lib.rs`) should be completely removed. We keep constants in `runtime/common/src/constants.rs` file now. 
The `runtime/cere/constants/src/lib.rs` is out of use and is not imported by any crate currently.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere-dev/src/lib.rs
>  		pub babe: Babe,
To nee to increment the `spec_version` in `cere_dev` runtime.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere/src/lib.rs
>  	type PalletId = VerificationPalletId;
To nee to increment the `spec_version` in `cere` runtime.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere/src/lib.rs
> +	pallet_ddc_customers::migration::MigrateToV1<Runtime>,
`pallet_ddc_customers::migration::MigrateToV1` has been executed on Mainnet. You should remove it from the list.

2024-07-30 13:50 UTC, yahortsaryk commented on runtime/cere/src/lib.rs
>  	migrations::Unreleased,
You should see if any of `migrations::Unreleased` migrations have been applied to Mainnet. If yes, you should remove it from the list.

2024-07-30 18:04 UTC, aie0 commented
obsolete in favour of https://github.com/Cerebellum-Network/blockchain-node/pull/402

2024-07-30 18:04 UTC, closed without merging